apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    api: mgmt
    apiserver: "true"
  name: v1alpha1.mgmt.casa.io
spec:
  group: mgmt.casa.io
  groupPriorityMinimum: 2000
  insecureSkipTLSVerify: true
  service:
    name: mgmt
    namespace: '{{ .Release.Namespace }}'
  version: v1alpha1
  versionPriority: 10
