apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd-svc
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: etcd
    port: 2379
    targetPort: 2379
  selector:
    app: etcd
